apiVersion: v1 
kind: Service 
metadata: 
  name: user 
  namespace: roboshop 
spec: 
  selector: 
    app: user
    tier: app 
    project: roboshop 
  ports: 
  - name: user-port
    protocol: TCP
    port: 8080
    targetPort: 8080